### PR TITLE
Avoid runtime universe init during startup

### PR DESCRIPTION
**Pull request by dwijnand**
Instead of initialising the scala reflection runtime universe the first
time a ManagedLogger is created (aka, at start up), let's kick that down
the line and use the cached LogExchange.stringTypeTagSuccessEvent for
`def success`.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=develop&util=pull/234/head&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by dwijnand** [comment]
Spotted with async-profiler:
image

That's ManagedLogger creating the runtime universe during startup.

**Comment by eed3si9n** [comment]
This came up in https://github.com/sbt/util/pull/153 and https://github.com/sbt/util/pull/221.
Do you have some before and after comparison number, like loading akka build and exiting several times?

**Comment by eed3si9n** [comment]
Also note that the "develop" branch for util is now at sbt/sbt - https://github.com/sbt/sbt/blob/develop/internal/util-logging/src/main/scala/sbt/internal/util/ManagedLogger.scala

**Comment by dwijnand** [comment]
Yeah, I saw.  I'll move to sbt/sbt, which helps because I can build an sbt and give you an after number too.

**Comment by dwijnand** [comment]
OK, in develop the runtime universe is warmed up in the ClassLoaderWarmup (on another thread).  Even removing that it gets warmed up by `TaskProgress` sending a log message and needing a TypeTag for itself.  So I stopped there.

**Pull request closed without merging**
