### PR TITLE
Cleaned up the deprecation messages to point to the correct classes.

### PR DESCRIPTION
**Pull request by tom-walford**
Just cleaned up some deprecation messages so they point to the correct classes, threw me when I first migrated :)

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/122/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/118/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-1.x-1.x-pull/122/head-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/118/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@22b7d582cc87e0874c8c0d86520c953f5ae4da87
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@8a76116ab005e5d369fa5eb8fedc4c4195c90dd0
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@539a2162e151d5e64feed135d2816ab40a808349
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@9abaa9f7407cc0f0e53bedc1348bdc1887efb888
  util              | <A HREF="https://github.com/sbt/util/pull/122">pull/122/head       </A> | sbt/util@83433d40e60c872395afa5d07c7e5a35c321be6b
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=1.x&util=pull/122/head&website=1.x&deploy_to_bintray=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by dwijnand** [comment]
We need [tut](https://github.com/tpolecat/tut) for deprecation message /cc @tpolecat ;-)

Thank you for the contribution, @tom-walford.

**Pull request merged**
