### PR TITLE
Remove unnecessary F0, F1 and Maybe

### PR DESCRIPTION
**Pull request by jvican**
`F0`, `F1` and `Maybe` have become useless since Java 8 introduced
`Supplier`, `Function` and `Optional` in the default Java 8 standard
library.

Therefore, they are not necessary anymore. This change is required to
change some Zinc's and sbt APIs. They are not widely used, so the
changes will be small.

### CODE REVIEW

**Comment by jvican** [comment]
Review by @eed3si9n and @dwijnand. This is an important and required change for the new Zinc API.

**Comment by stuhood** [comment]
#shipit

**Comment by eed3si9n** [comment]
Could you have the ripple PRs lined up and validated with Dbuild plz? https://jenkins.scala-sbt.org:8592/job/sbt%20validator/build

The parameter screen should look like this https://jenkins.scala-sbt.org:8592/job/sbt%20validator/40/parameters/

**Comment by jvican** [comment]
@eed3si9n We need to find a better solution than that. It's sad we're doing this just to emulate monorepo, it creates lots of overhead.
  
On a similar note, I tried to validate the PR but I must be logged in with my the scala sbt account or someone has to give me rights.

**Review by dwijnand — APPROVED** [review]
LGTM, thanks.

**Comment by jvican** [comment]
Can we ship this @eed3si9n ?

**Comment by eed3si9n** [comment]
I would love to merge this if there are passing ripple PRs. Otherwise, someone else would end up doing the integration work.

**Comment by jvican** [comment]
Right, is there any reason why the lightbend validator hasn't run here?

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/80/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-1.0-1.0-1.0-pull/84/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/80/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@5f2e5cf10ef1a0fb73d149b46b71b1c5111f30a7
  zinc              | 1.0                  | sbt/zinc@1e6893685583f1ecd33d0bd862545ff6552de78a
  io                | 1.0                  | sbt/io@16c2e3100ade4c4e6dfec83bcf8d5bce6506a773
  librarymanagement | 1.0                  | sbt/librarymanagement@f8d3718d283cacdc11c6d4a9f101c675f687dc49
  util              | pull/84/head         | sbt/util@eda6b7ebae81c20ea01a523f3a8a7ba7fe1d29e9
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=1.0&io=1.0&librarymanagement=1.0&util=pull/84/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by eed3si9n** [comment]
Here you go - https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/84/head&deploy_to_bintray=false

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/91/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-1.0-1.0-1.0-pull/84/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/91/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.0.x">1.0.x               </A> | sbt/sbt@716d664d64d183384408734fa570e63e1a21f99e
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.0">1.0                 </A> | sbt/zinc@aabdd7a7e4c58cc4173b52c1f55e58a11a545cb4
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@f55849d988b94941309d316c43533b0af423f244
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.0">1.0                 </A> | sbt/librarymanagement@f8d3718d283cacdc11c6d4a9f101c675f687dc49
  util              | <A HREF="https://github.com/sbt/util/pull/84">pull/84/head        </A> | sbt/util@eda6b7ebae81c20ea01a523f3a8a7ba7fe1d29e9
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=1.0&io=1.0&librarymanagement=1.0&util=pull/84/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/84/head&deploy_to_bintray=false">this link.</A>

**Comment by jvican** [comment]
I have just finished doing two ripple PRs against sbt/sbt and sbt/zinc to validate this change, but realized that since Zinc hasn't been released yet with the new logging API, the validation is going to fail because my PR to sbt/zinc depends on this new API.
  
Can someone validate these PRs manually? They compile fine locally, except for the compilation failures in the logging API. I would like to get this in.

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/97/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/3317/head-pull/359/head-1.0-pull/122/head-pull/84/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/97/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/3317">pull/3317/head      </A> | sbt/sbt@26cfe0cb7b75c39c10377f83896a01d14411eb93
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/359">pull/359/head       </A> | sbt/zinc@6ef476b25226feee78a01b68e1f4f39e2c121d20
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@f55849d988b94941309d316c43533b0af423f244
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/122">pull/122/head       </A> | sbt/librarymanagement@e3891c8732dc248bd3ff3be9d5c796454d66bc3a
  util              | <A HREF="https://github.com/sbt/util/pull/84">pull/84/head        </A> | sbt/util@18a73db57d8699d487918ed0ad441db3d3848854
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=pull/3317/head&zinc=pull/359/head&io=1.0&librarymanagement=pull/122/head&util=pull/84/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
