### PR TITLE
Fix logger printing too many newlines

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/98/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/101/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-1.0-1.0-1.0-pull/98/head-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/101/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.0.x">1.0.x               </A> | sbt/sbt@53b9ce2d712088c4019cac25b4726fb8f815f3cc
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.0">1.0                 </A> | sbt/zinc@d4d29e8ffeecfa7c6a8e834b4ee54c4bfda9af63
  io                | <A HREF="https://github.com/sbt/io/tree/1.0">1.0                 </A> | sbt/io@49a9cea2906ecb62ea690b5d5dddc257e0ada151
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.0">1.0                 </A> | sbt/librarymanagement@0147e0c77578ca4852137a6113bcac4c7adeeb38
  util              | <A HREF="https://github.com/sbt/util/pull/98">pull/98/head        </A> | sbt/util@28ab7ac79de4883f72cd5f00224971a7cd4e02c9
  website           | <A HREF="https://github.com/sbt/website/tree/1.0.x">1.0.x               </A> | sbt/website@c5ef5f0dc6cd84c6c6977c09484f56113eaad0d7

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=1.0&io=1.0&librarymanagement=1.0&util=pull/98/head&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by Duhemm** [comment]
I think that there may be something wrong with dbuild...?

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
@cunei Please could you have a look at this failure? There's no way this change makes something fail to compile.

I'm happy to merge this without ripples.

**Comment by cunei** [comment]
@dwijnand I tried `sbt-allsources.sh` locally on my machine, with the same commits, and I get the same outcome.

**Pull request merged**
