### PR TITLE
Contraband 0.3.0-M7, and transitive ScalaJSON

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/88/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/88/head&deploy_to_bintray=false">this link.</A>

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
Didn't merge in case I shouldn't (e.g pseudo-mono-repo reasons)

**Comment by eed3si9n** [comment]
lol. That is our new struggle.

**Pull request merged**
