### PR TITLE
package name change and test migration

### PR DESCRIPTION
**Pull request by eed3si9n**
/review @jsuereth, @dwijnand

### CODE REVIEW

**Comment by dwijnand** [comment]
I think sbt.util.internal is right though. Allows for accessing util-only things, as opposed to non-util-specific internal-only things.. which doesn't exist.

**Comment by eed3si9n** [comment]
The encapsulation boundary is between `sbt` the-API, and `sbt.internal` the-implementation.
Util layer in particular provides common utility classes that are used by other implementations, for example `UnitSpec` for unit tests. `sbt.util.internal` implies that other layers can't/won't access it.

**Comment by dwijnand** [comment]
Ah. So it's not internal to the module, it's internal to the entirety of sbt.. interesting.

**Comment by eed3si9n** [comment]
Yea. That allows internal typeclass/datatype like `ShowLines` to be shared across modules. It's more intertwined but the alternative would be exposing `ShowLines` to public, which I don't think is necessary. Layering does enforce that IO doesn't depend on anything else even in the internals, Util only depends on IO, etc.

**Comment by eed3si9n** [comment]
I am exposing `sbt.util.Logger` and a few of its friends. 0.1.0-M3 is pushed out of this.

**Pull request merged**
