### PR TITLE
Cleanup `ConsoleAppender`

### PR DESCRIPTION
**Pull request by Duhemm**
With that changes, the `ConsoleAppender` can now always receive formatted strings and it will remove escape sequences if it is not supposed to output colors. Also, add some documentation and clean up the code.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/91/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/91/head&deploy_to_bintray=false">this link.</A>

**Comment by eed3si9n** [comment]
Is it possible to reduce the scope of this PR so it's bincompat and still fixes the escaping?
util is lower in the food chain, so merging breaking change will going to burn a few days of validating.

**Comment by Duhemm** [comment]
Doesn't that mean that we'll be stuck with the fully exposed implementation details for the whole lifetime of sbt 1.x?

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/91/head&deploy_to_bintray=false">this link.</A>

**Comment by eed3si9n** [comment]
Are there ripple PRs on this? There are several breaking changes on util now, so I am more willing to merge this in if there are ripple PRs.

**Pull request merged**
