### PR TITLE
Delegate ansiCodesSupported to ConsoleAppender

### PR DESCRIPTION
**Pull request by liff**
Fixes sbt/sbt#3336.

### CODE REVIEW

**Comment by liff** [comment]
Couldn't figure out an obvious way to write a test for this since `ConsoleAppender.formatEnabledInEnv` is static :(

**Review by dwijnand — APPROVED** [review]
LGTM, but @eed3si9n WDYT?

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Thanks for figuring out what's broken.

The new logger, based on log4j separates the concern of the log producer (Logger) and the handlers that takes actions (Appender, e.g for displaying on Console). Color support I think is a console concern, so if we're filtering it out, that should move to appender.

I think we should deprecate  ansiCodesSupported from the logger and always return `true`, and fix https://github.com/sbt/util/blob/1.x/internal/util-logging/src/main/scala/sbt/internal/util/MultiLogger.scala

**Comment by liff** [comment]
So, should I change this PR to deprecate `ansiCodesSupported`? Not sure what you mean by fixing `MultiLogger`.

**Review by eed3si9n — APPROVED** [review]
Let me merge this as is, and I'll worry about the rest of the situation.

**Pull request merged**
