### PR TITLE
Avoid temporary string, array in JSON reading

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.2.x&zinc=1.2.x&io=1.2.x&librarymanagement=1.2.x&util=pull/186/head&website=1.2.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by retronym** [comment]
Collateral progress from some unrelated profiling I was doing of scalac.

**Comment by retronym** [comment]
Here's the size of the JSON update report files in `guardian/frontend`.

```
$ find . -type f | grep update_cache_2.12  | xargs ls -lahS
-rw-r--r--  1 jz  staff   8.8M Oct  9 15:31 ./preview/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./identity/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./diagnostics/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./facia/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./applications/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./commercial/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./archive/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.2M Oct  9 15:32 ./onward/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.1M Oct  9 15:32 ./common/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   8.0M Oct  9 15:32 ./sport/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   6.7M Oct  9 15:32 ./facia-press/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   6.2M Oct  9 15:32 ./article/target/streams/$global/update/$global/streams/update_cache_2.12/output
-rw-r--r--  1 jz  staff   4.9M Oct  9 15:35 ./project/target/streams/$global/update/$global/streams/update_cache_2.12/output
...
```

**Comment by retronym** [comment]
It appears that the JSON format stores the transitive callers for each node, which would require `O(N^2)` space wrt the depth of the graph. A better fix would be to look at the use cases for this data, and drop parts that aren't needed, and then refactor to store edges only and reconstruct the transitive links on the fly.

```json
{
  "cachedDescriptor": "file:///Users/jz/code/guardian-frontend/preview/target/scala-2.12/resolution-cache/com.gu/preview_2.12/0.1.0-SNAPSHOT/resolved.xml.xml",
  "configurations": [
    {
      "configuration": {
        "name": "compile"
      },
      "modules": [
        {
          "module": {
            "organization": "org.scala-lang",
            "name": "scala-library",
            "revision": "2.12.8-bin-4c77697",
            "isChanging": false,
            "isTransitive": true,
            "isForce": false,
            "explicitArtifacts": [],
            "inclusions": [],
            "exclusions": [],
            "extraAttributes": {},
            "crossVersion": {
              "type": "Disabled"
            }
          },
          "artifacts": [
            [
              {
                "name": "scala-library",
                "type": "pom",
                "extension": "pom",
                "configurations": [],
                "extraAttributes": {}
              },
              "file:///Users/jz/.ivy2/local/org.scala-lang/scala-library/2.12.8-bin-4c77697/poms/scala-library.pom"
            ],
            [
              {
                "name": "scala-library",
                "type": "jar",
                "extension": "jar",
                "configurations": [],
                "extraAttributes": {}
              },
              "file:///Users/jz/.ivy2/local/org.scala-lang/scala-library/2.12.8-bin-4c77697/jars/scala-library.jar"
            ]
          ],
          "missingArtifacts": [],
          "status": "release",
          "publicationDate": "2018-10-08T10:22:46+10:00",
          "resolver": "sbt-chain",
          "artifactResolver": "sbt-chain",
          "evicted": false,
          "homepage": "http://www.scala-lang.org",
          "extraAttributes": {},
          "isDefault": false,
          "configurations": [
            {
              "name": "test"
            },
            {
              "name": "sources"
            },
            {
              "name": "runtime(*)"
            },
            {
              "name": "provided"
            },
            {
              "name": "master(compile)"
            },
            {
              "name": "runtime"
            },
            {
              "name": "default(compile)"
            },
            {
              "name": "optional"
            },
            {
              "name": "compile(*)"
            },
            {
              "name": "pom"
            },
            {
              "name": "default"
            },
            {
              "name": "master(*)"
            },
            {
              "name": "compile"
            },
            {
              "name": "docs"
            }
          ],
          "licenses": [
            [
              "BSD 3-Clause",
              "http://www.scala-lang.org/license.html"
            ]
          ],
          "callers": [
            {
              "caller": {
                "organization": "com.beachape",
                "name": "enumeratum-play-json_2.12",
                "revision": "1.5.12",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "default"
                },
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                },
                {
                  "name": "master"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "com.gu",
                "name": "play-googleauth_2.12",
                "revision": "0.7.0",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "default"
                },
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                },
                {
                  "name": "master"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "com.typesafe.play",
                "name": "play-ws-standalone_2.12",
                "revision": "1.1.3",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "com.typesafe.akka",
                "name": "akka-contrib_2.12",
                "revision": "2.5.6",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {
                  "info.apiURL": "http://doc.akka.io/api/akka/2.5.6"
                },
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "default"
                },
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                },
                {
                  "name": "master"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "org.scala-lang.modules",
                "name": "scala-java8-compat_2.12",
                "revision": "0.8.0",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "com.typesafe.play",
                "name": "filters-helpers_2.12",
                "revision": "2.6.7",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "default"
                },
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                },
                {
                  "name": "master"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "org.scala-lang.modules",
                "name": "scala-xml_2.12",
                "revision": "1.0.6",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
            {
              "caller": {
                "organization": "com.typesafe.play",
                "name": "play-ws-standalone-xml_2.12",
                "revision": "1.1.3",
                "isChanging": false,
                "isTransitive": true,
                "isForce": false,
                "explicitArtifacts": [],
                "inclusions": [],
                "exclusions": [],
                "extraAttributes": {},
                "crossVersion": {
                  "type": "Disabled"
                }
              },
              "callerConfigurations": [
                {
                  "name": "compile"
                },
                {
                  "name": "runtime"
                }
              ],
              "callerExtraAttributes": {},
              "isForceDependency": true,
              "isChangingDependency": false,
              "isTransitiveDependency": true,
              "isDirectlyForceDependency": false
            },
   ...
```

**Comment by retronym** [comment]
My profile showed ~36% of the CPU time of:


```
$ sbt -J-XX:+UnlockCommercialFeatures -J-XX:+FlightRecorder -J-XX:FlightRecorderOptions=stackdepth=2048 -J-XX:+UnlockDiagnosticVMOptions -Dsun.reflect.inflationThreshold=0 -J-XX:+DebugNonSafepoints -J-Xmx3G

[root] $ ;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile;cleanClasses;test:cleanClasses;test:compile
```

Was spent in update report JSON deserialization.

That seems crazy high, and might be a measurement error, or might just be what happens when large classpaths push the `N` in `O(N^2)` enough.

**Comment by eed3si9n** [comment]
I've heard similar reports on how high the update report serialization cost is. I'd be open to alternative formats and/or being more choosy about what to take out of the freezer and thawing it out.

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1076/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.2.x-1.2.x-1.2.x-1.2.x-pull/186/head)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1076/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.2.x">1.2.x               </A> | sbt/sbt@fb4a4a3c3027f276e7365c03cc5ea6951c2e92fe
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.2.x">1.2.x               </A> | sbt/zinc@b62282b75c875189442d3946240852f9792db889
  io                | <A HREF="https://github.com/sbt/io/tree/1.2.x">1.2.x               </A> | sbt/io@d0a15612b8d8a627e25d300ee841a7369298ad25
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.2.x">1.2.x               </A> | sbt/librarymanagement@37edc11123f91ed89a7b58075921532476d5d7e4
  util              | <A HREF="https://github.com/sbt/util/pull/186">pull/186/head       </A> | sbt/util@aaf8427037866fcb0a2382b1c6172786fa4251d2

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.2.x&zinc=1.2.x&io=1.2.x&librarymanagement=1.2.x&util=pull/186/head&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
The dbuild failure looks unrelated.

**Review by eed3si9n — APPROVED** [review]

**Comment by retronym** [comment]
> I've heard similar reports on how high the update report serialization cost is. I'd be open to alternative formats and/or being more choosy about what to take out of the freezer and thawing it out.

@eed3si9n Looks like you've down a round of trimming of unneeded `callers` entries in https://github.com/sbt/librarymanagement/commit/e430139680d6b91bf00ec3e15d4dea55c0a87fad

**Pull request merged**
