### PR TITLE
Remove modules that have moved back to sbt/sbt

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?util=pull/90/head&deploy_to_bintray=false">this link.</A>

**Comment by Duhemm** [comment]
Now that the "symmetric PR" has been merged in sbt/sbt, I guess we should merge that ASAP to get unblocked?

**Comment by dwijnand** [comment]
Unblocked from what? :)

Imho we should merge this asap before the sources here start diverging.

**Comment by eed3si9n** [comment]
Merged

**Pull request merged**
