### PR TITLE
Output Caching: invoke output value function again, after executing output effect

### LINKED ISSUE #168: Output Caching caches value from before effect function is called, not after
In 0.13, the output value `() ⇒ A1` function is called twice, [including after the call to `f: (Boolean, A1) => A2`](https://github.com/sbt/sbt/blob/1562cea1d0090a3b5ab85c385970c6cceaf7cdba/cache/tracking/src/main/scala/sbt/Tracked.scala#L87) (the function signature was `(Boolean, I) ⇒ O` in 0.13).

This changed in 1.x, so now the output value function `p` is only called once and assigned to a value. 

https://github.com/sbt/util/blob/3811d2a82eec5a0d5531faba651372b37a5a81e0/util-tracking/src/main/scala/sbt/util/Tracked.scala#L98-L103

This changes the behavior of the caching function. For example, files that did not exist prior to the call to `f` but were created by `f` are now cached as missing, where there would have been cached as created in 0.13. (I believe this is the root cause of https://github.com/sbt/sbt-assembly/issues/289 and https://github.com/Dwolla/sbt-s3-publisher/issues/11.)

I think I have a fix for the issue, but I'm having trouble using the locally built version of sbt to run scripted tests for sbt-assembly. (It seems to be using my local `1.2.0-SNAPSHOT` version of sbt but with the `1.2.0-M2` version of the `util-tracking` jar, not the local one.) I'll probably push up a PR anyway, to try to move things forward.

### PR DESCRIPTION
**Pull request by bpholt**
fixes #168

This is a little earlier than I would normally create a PR, but I'm having trouble locally using the snapshot version of this library in a scripted test for the sbt plugin where this issue first came up. I'm hoping to get some feedback from maintainers (and any CI for the project) and will proceed accordingly.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=1.x&util=pull/169/head&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by eed3si9n** [comment]
It would be good to add a unit test for this bad bug.

**Comment by bpholt** [comment]
I agree—I’m hoping I’ll have something to add to the PR tomorrow.

**Comment by bpholt** [comment]
@eed3si9n I updated the output caching tests to catch the bug. I also went through and cleaned up a bunch of compiler warnings in the util-tracking project, but I committed those changes separately in case you want to remove them and let this PR focus on the core change.

**Comment by eed3si9n** [comment]
Awesome. I am happy to merge this.

**Pull request merged**
